#!/usr/bin/env bash

set -ex

PROD_NAME=${PRODUCT#"cbdeps::"}
PROD_PATH=${PRODUCT//::/\/}
cd ${WORKSPACE}

env

if [ -z "${PLATFORM}" ]; then
    echo "Must set PLATFORM in environment"
    exit 1
fi

# Hacky support for cross-compiling Windows
if [[ "${PLATFORM}" =~ -windowscrosscompile$ ]]; then
    echo "CROSS COMPILING FOR WINDOWS!"
    export PLATFORM=windows_msvc2017
    export ARCH=amd64
else
    export ARCH=x86_64
fi
TARBALL_NAME=${PROD_NAME}-${PLATFORM}-${ARCH}-${VERSION}-${BLD_NUM}.tgz
MD5_NAME=${PROD_NAME}-${PLATFORM}-${ARCH}-${VERSION}-${BLD_NUM}.md5

echo "Performing build..."
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BASE_DIR=$(dirname ${SCRIPT_DIR})  # Need 'cbdeps' directory
INSTALL_DIR=${WORKSPACE}/install
rm -rf ${INSTALL_DIR}
mkdir -p ${INSTALL_DIR}
${BASE_DIR}/${PROD_NAME}/${PROD_NAME}_unix.sh ${INSTALL_DIR} ${PLATFORM} ${RELEASE} ${VERSION} ${BLD_NUM}

echo "Preparing for package..."
PACKAGE=${BASE_DIR}/${PROD_NAME}/package
if [ -d ${PACKAGE} ]; then
    cp -pr ${PACKAGE}/* ${INSTALL_DIR}
fi

echo "Create package..."
PKG_DIR=${WORKSPACE}/packages/${PROD_NAME}/${VERSION}/${BLD_NUM}
rm -rf ${PKG_DIR}
mkdir -p ${PKG_DIR}
cd ${INSTALL_DIR}
tar zcf ${PKG_DIR}/${TARBALL_NAME} .
md5sum ${PKG_DIR}/${TARBALL_NAME} > ${PKG_DIR}/${MD5_NAME}
