#!/bin/bash -xe

# This is a moderately hacky script to update a github.com/couchbasedeps
# repository from the upstream it was originally forked from. It is
# intended primarily for the Jenkins job
# http://server.jenkins.couchbase.com/job/update-couchbasedep

PROJECT=$1

if ${FORCE}; then
  FORCE="--force"
fi

# PCRE's upstream is still svn, so the update process is totally different
case "$PROJECT" in
  pcre)
    pushd `dirname $0` > /dev/null
    SCRIPTPATH=`pwd -P`
    popd > /dev/null
    ${SCRIPTPATH}/update-cbdep-svn2github ${PROJECT}
    exit
    ;;
esac

python3.6 -m venv update_cbdep
. ./update_cbdep/bin/activate
pip install requests

git clone ssh://git@github.com/couchbasedeps/${PROJECT}
cd ${PROJECT}

upstream_url=$( python <<EOF
import requests
resp = requests.get("https://api.github.com/repos/couchbasedeps/${PROJECT}")
print (resp.json()['parent']['clone_url'])
EOF
)

if [ ${PROJECT} = "erlang" ]; then
    upstream_url=ssh://git@github.com/erlang/otp
elif [ ${PROJECT} = "breakpad" ]; then
    upstream_url=ssh://git@github.com/google/breakpad
fi

git remote add upstream ${upstream_url}
git fetch --all --tags ${FORCE}
git push --tags origin 'refs/remotes/upstream/*:refs/heads/*' ${FORCE}
