#!/bin/bash

gpg --import /etc/apt/trusted.gpg.d/GPG-KEY-COUCHBASE-1.0
apt-key add /etc/apt/trusted.gpg.d/GPG-KEY-COUCHBASE-1.0

distrib=$(lsb_release -c | awk '{print $2}')

if ! [[ "$distrib" =~ ^(wheezy|jessie|stretch|precise|trusty|xenial)$ ]]; then
    echo "Supported platforms are: Debian/wheezy,jessie,stretch and Ubuntu/precise,trusty,xenial"
    exit 1
else
    sed -e "s/%DCODE_SERVER%/$distrib/g" -e "s/%DCODE_SDK%/$distrib/g" \
        -i /etc/apt/sources.list.d/couchbase.list
    exit 0
fi
