#!/bin/bash

distrib=$(lsb_release -c | awk '{print $2}')

if ! [[ "$distrib" =~ ^(wheezy|jessie|stretch|precise|trusty|xenial|bionic)$ ]]; then
    echo "Supported platforms are: Debian/wheezy,jessie,stretch and Ubuntu/precise,trusty,xenial,bionic"
    exit 1
else
    exit 0
fi
