#!/bin/bash -ex

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${SCRIPT_DIR}/../utilities/shell-utils.sh

usage() {
    echo "Usage: $(basename $0) -m MANIFEST [ -u MANIFEST_REPO ] [ -p PROJECT1,PROJECT2,... ] [-n] [-f] [-l]"
    echo "  -p - comma-separated list of projects to update (default is all 'bsl' projects)"
    echo "  -n - dry run; report any possible problems but don't push changes"
    echo "  -f - force change existing BSL licenses to VERSION (will NOT overwrite PRODUCT)"
    echo "  -l - license only; do not update source code header comments"
    exit 1
}

# Extract metadata from 'build' repo in manifest
get_metadata() {
    cmd='echo ${REPO__'${1}'}'
    result=$(repo forall build -c "${cmd}")
    if [ -z "${result}" ]; then
        error "Manifest ${MANIFEST} is missing ${1} annotation!"
    fi
    echo "${result}"
}

MANIFEST_REPO=https://github.com/couchbase/manifest
DRY_RUN_ARG=
FORCE_ARG=
LICENSE_ONLY_ARG=
PROJECTS_ARG=
while getopts ":u:m:p:nfl" opt; do
    case ${opt} in
        u)
            MANIFEST_REPO=${OPTARG}
            ;;
        m)
            MANIFEST=${OPTARG}
            ;;
        p)
            PROJECTS_ARG=${OPTARG//,/ }
            ;;
        n)
            DRY_RUN_ARG=-n
            ;;
        f)
            FORCE_ARG=-f
            ;;
        l)
            LICENSE_ONLY_ARG=-l
            ;;
        \?)
            usage
            ;;
        :)
            echo "-${OPTARG} requires an argument"
            usage
            ;;
    esac
done

chk_set MANIFEST

# Sync manifest locally
status Syncing manifest ${MANIFEST}...
MANIFEST_DIR=${MANIFEST//\//_}
mkdir -p ${MANIFEST_DIR}
cd ${MANIFEST_DIR}
repo init --no-repo-verify -u ${MANIFEST_REPO} -m ${MANIFEST} -g bsl,build
repo sync --jobs=8
repo forall -c 'git clean -dfx && git reset --hard'
status Done syncing
echo

# Extract metadata from manifest
PRODUCT=$(get_metadata BSL_PRODUCT)
VERSION=$(get_metadata BSL_VERSION)
CHANGE_DATE=$(get_metadata BSL_CHANGE_DATE)

status
status Updating BSL license to $PRODUCT Version $VERSION, change date $CHANGE_DATE
status
repo forall -v -g bsl -p ${PROJECTS_ARG} -c \
    "${SCRIPT_DIR}/update-bsl-for-repo" \
        ${DRY_RUN_ARG} ${FORCE_ARG} ${LICENSE_ONLY_ARG} \
        -p "${PRODUCT}" \
        -v "${VERSION}" \
        -d "${CHANGE_DATE}"
