#!/bin/bash -ex

# This will sync a historic build manifest and create a source tarball for it
# in the current directory, along with build.properties,
# build-properties.json, and build-manifest.xml. The build properties files
# will contain only basic build information; see
# build-tools/utilities/sync_historic_manifest for details.

PRODUCT=$1
RELEASE=$2
VERSION=$3
BLD_NUM=$4

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "${SCRIPT_DIR}/../utilities/shell-utils.sh"
WORKDIR=$(pwd)

chk_set PRODUCT
chk_set RELEASE
chk_set VERSION
chk_set BLD_NUM

"${SCRIPT_DIR}/../utilities/sync_historic_manifest" \
    ${PRODUCT} ${RELEASE} ${VERSION} ${BLD_NUM} ./src

cd src
echo "Creating source tarball"
echo =======================
tar czf ../source.tar.gz .[A-z]* *
