#!/usr/bin/env bash
set -e

# Get the root of the repository
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$( cd "$SCRIPT_DIR/../../../" && pwd )"

# Clone the tlm repository
$REPO_ROOT/utilities/clean_git_clone https://github.com/couchbase/tlm

./main.py
