FROM {{ baseimage }}

ARG RPMFILE=couchbase-{{ target }}-{{ version }}-{{ bld_num }}.noarch.rpm
COPY ${RPMFILE} /tmp
RUN set -x \
    && yum install -y /tmp/${RPMFILE} \
    && yum search --showduplicates -y couchbase-server | grep couchbase-server | tee /tmp/output.txt

{% if target == "release" %}
RUN set -x \
    && fgrep {{ testver1 }} /tmp/output.txt \
    && fgrep {{ testver2 }} /tmp/output.txt \
    && fgrep 7.2.0 /tmp/output.txt
{% endif %}
