FROM {{ baseimage }}

ARG DEBFILE=couchbase-{{ target }}-{{ version }}-{{ bld_num }}-noarch.deb
COPY ${DEBFILE} /tmp
RUN set -x \
    && apt-get update \
    && apt-get install -y /tmp/${DEBFILE} \
    && apt-get update \
    && apt list -a couchbase-server | grep couchbase-server | tee /tmp/output.txt

{% if target == "release" %}
RUN set -x \
    && fgrep {{ testver1 }} /tmp/output.txt \
    && fgrep {{ testver2 }} /tmp/output.txt \
    && fgrep 7.2.0 /tmp/output.txt
{% endif %}
