#!/bin/bash -ex

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "${SCRIPT_DIR}/../utilities/shell-utils.sh"

if [ ! -z "$1" ]; then
    PRODUCT=$1
    RELEASE=$2
    VERSION=$3
    BLD_NUM=$4
fi

chk_set PRODUCT
chk_set RELEASE
chk_set VERSION
chk_set BLD_NUM

# Derived values
PRODUCT_PATH=${PRODUCT/:://}
PRODUCT_NAME=$(basename ${PRODUCT_PATH})
ROOT=http://latestbuilds.service.couchbase.com/builds/latestbuilds/${PRODUCT_PATH}/${RELEASE}/${BLD_NUM}

# Per CBD-4179, AWS agents will always have a /aws dir.
if [ -d /aws ]; then

    # Repo sync using build manifest
    "${SCRIPT_DIR}/../utilities/sync_historic_manifest" \
        ${PRODUCT} ${RELEASE} ${VERSION} ${BLD_NUM}

else
    # Downloads from latestbuilds

    PROP=${PRODUCT_NAME}-${RELEASE}-${BLD_NUM}.properties
    echo "Downloading ${PROP}..."
    curl --fail --retry 5 -s -L -o build.properties ${ROOT}/${PROP}

    SRC=${PRODUCT_NAME}-${VERSION}-${BLD_NUM}-source.tar.gz
    echo "Downloading ${SRC}..."
    curl --fail --retry 5 -s -LO ${ROOT}/${SRC}

    echo "Extracting source..."
    tar xzf ${SRC}
fi
