#!/bin/bash -e

if [ ! -z "$1" ]; then
    PRODUCT=$1
    RELEASE=$2
    VERSION=$3
    BLD_NUM=$4
fi

if [ -z "${PRODUCT}" ]; then
    echo Missing PRODUCT
    exit 1
fi
if [ -z "${RELEASE}" ]; then
    echo Missing RELEASE
    exit 1
fi
if [ -z "${VERSION}" ]; then
    echo Missing VERSION
    exit 1
fi
if [ -z "${BLD_NUM}" ]; then
    echo Missing BLD_NUM
    exit 1
fi

# Derived values
PRODUCT_PATH=${PRODUCT/:://}
PRODUCT_NAME=$(basename ${PRODUCT_PATH})
ROOT=http://latestbuilds.service.couchbase.com/builds/latestbuilds/${PRODUCT_PATH}/${RELEASE}/${BLD_NUM}

# Downloads

PROP=${PRODUCT_NAME}-${RELEASE}-${BLD_NUM}.properties
echo "Downloading ${PROP}..."
curl --fail --retry 5 -s -L -o build.properties ${ROOT}/${PROP}

SRC=${PRODUCT_NAME}-${VERSION}-${BLD_NUM}-source.tar.gz
echo "Downloading ${SRC}..."
curl --fail --retry 5 -s -LO ${ROOT}/${SRC}

echo "Extracting source..."
tar xzf ${SRC}
